Task/20
Defuera/CryptoBot pull request #22
Opened 2017-10-02 20:13 UTC by VasyaFromRussia

2017-10-02 20:51 UTC, Defuera requested changes

2017-10-02 20:51 UTC, Defuera commented on build.gradle
> +    ext.kotlin_version = '1.1.51'
а че там новенького?

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
> +        sendMessage(chatId, Request.ABOUT.handler())
я изначально так сделал, но потом решил, что это не правильно, тк сообщение может быть любым. 

Те сообщение это всегда текст, но не всегда `RequestHandler`. 

Так что не уверен, что обратно стоит возвращатся..

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
> +    val requestHandler = Request.handler(message.text())
`handler` - странное название для метода, имхо не говорящее

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
> +private fun sendMessage(chatId: Long, outcomingMessage: String) {
аа, вот оно что, теперь есть два метода;; Ну тогда да, тогда норм. Возможно только первый лучше назвать по-другому. Но на этот счет я не уверен. Решай сам;

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/About.kt
> +internal object About : RequestHandler {
👍

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/Help.kt
> +internal object Help : RequestHandler {
👍

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/Price.kt
> +    private val exchange = ExchangeFacade() //todo inject with dagger based on user preferences?
а чего параметр то снизу оказался? Давай наверх его..

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/Request.kt
> +        override fun help(): String = "help hleb"
description?

2017-10-02 20:51 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/Request.kt
> +enum class Request(val pattern: String) {
👍

2017-10-02 21:04 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/Request.kt
> +enum class Request(val pattern: String) {
Вот только название мне не нравится. Пересекается с network Request. Я думал тогда как-то по другому назвать. Но ничего в голову не пришло. Давай еще подумаем...

Это запрос от пользователя.. Может быть заявка? Либо SupportedCommand. Либо просто Команда.. 

UnsuppordedCommand не может быть SupportedCommand. поэтому предлагаю назвать Command

2017-10-03 09:21 UTC, VasyaFromRussia commented on build.gradle
> +    ext.kotlin_version = '1.1.51'
ничего особенного, как мне показалось
https://blog.jetbrains.com/kotlin/2017/09/kotlin-1-1-50-is-out/

2017-10-03 09:22 UTC, VasyaFromRussia commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
> +    val requestHandler = Request.handler(message.text())
```getCommandHandler()``` - норм?

2017-10-03 09:24 UTC, VasyaFromRussia commented on src/main/kotlin/ru/justd/cryptobot/handler/Price.kt
> +    private val exchange = ExchangeFacade() //todo inject with dagger based on user preferences?
упс, это какие-то тёмные силы

2017-10-03 09:24 UTC, VasyaFromRussia commented on src/main/kotlin/ru/justd/cryptobot/handler/Request.kt
> +enum class Request(val pattern: String) {
да, Command мне нравится

2017-10-03 09:24 UTC, VasyaFromRussia commented on src/main/kotlin/ru/justd/cryptobot/handler/Request.kt
> +        override fun help(): String = "help hleb"
согласен

2017-10-03 09:34 UTC, VasyaFromRussia commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
> +private fun sendMessage(chatId: Long, outcomingMessage: String) {
Я пока не могу придумать, как его назвать. По сути, сейчас там единственный метод - получение сообщения для ответа, так что пока смысл не нарушается. Но если будет идея лучшего названия - пожалуйста.

2017-10-03 10:13 UTC, Defuera approved these changes

2017-10-03 10:13 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/Price.kt
> +internal class Price private constructor(private val currencyCode: String) : RequestHandler {
Давай так не будем называть. Price хорошее имя для POJO, а для RequestHandler (CommandHandler) хорошее имя PriceCommandHandler

2017-10-03 12:23 UTC, merged