command handler facade; provide exchange facade via dagger
Defuera/CryptoBot pull request #35
Opened 2017-10-06 22:40 UTC by VasyaFromRussia

2017-10-06 22:42 UTC, VasyaFromRussia commented on src/main/kotlin/ru/justd/cryptobot/handler/CommandHandlerFacade.kt
> +    lateinit var exchange: ExchangeFacade
тут факап с нэймингом, потому что exchageFacade клэшится с таким же полем в PriceCommandHandlerFactory

2017-10-07 02:02 UTC, Defuera requested changes

2017-10-07 02:02 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/di/MainComponent.kt
> +    fun inject(commandHandlerFacade: CommandHandlerFacade)
Учитывая 1,2,3,4,5 это надо отсюда убрать

2017-10-07 02:02 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/di/MainModule.kt
> +    fun provideCommandHandlerFacade(): CommandHandlerFacade = CommandHandlerFacade()
1 Раз CommandHandlerFacade в графе, то зависимости ему лучше передать через конструктор, прямо из модуля.

2017-10-07 02:02 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/handler/CommandHandlerFacade.kt
> +        Main.component.inject(this)
2 Из этого следует, что тут не нужен Main.Component.inject

2017-10-07 02:02 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
> +        lateinit var component: MainComponent
3 Из чего следует, что MainComponent можно вообще не класть в статическое поле

2017-10-07 02:02 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
> -        DaggerMainComponent.builder()
4 Из чего следует, что в Main можно не класть Component в поле вообще (верни oneliner)

2017-10-07 10:39 UTC, VasyaFromRussia commented
уговорил

2017-10-07 13:09 UTC, Defuera approved these changes

2017-10-07 13:09 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/di/MainComponent.kt
> +import ru.justd.cryptobot.handler.CommandHandlerFacade
бебебе

2017-10-07 13:09 UTC, Defuera commented on src/main/kotlin/ru/justd/cryptobot/Main.kt
>          val factory = Command.findCommandHandlerFactory(message.text())
может это тоже внутрь CMF засунуть?

2017-10-08 17:56 UTC, merged